# connection between pyaerocom and ACTRIS-EBAS variables
[variables]
#prototype
# the order in the list below is preserved and determines the order the data is read
#[variables.<pyaerocom var name>]
#actris_variable = [<list of actris variables>]
#actris_matrix = [<list of actris matrixes>]
#ebas_component = [<list of ebas component names>]
#ebas_matrix = [<list of ebas matrix names>]

[variables.conco3]
actris_variable = ["ozone mass concentration"]
actris_matrix = ["gas phase"]
ebas_component = ["ozone"]
ebas_matrix = ["air"]
standard_names = ["mass_concentration_of_ozone_in_air"]

[variables.vmro3]
#actris_variable = ["ozone amount fraction"]
actris_variable = ["ozone mass concentration"]
actris_matrix = ["gas phase"]
ebas_component = ["ozone"]
ebas_matrix = ["air"]
standard_names = ["mole_fraction_of_ozone_in_air"]


[variables.concso4t]
actris_variable = ["aerosol particle sulphate mass concentration"]
actris_matrix = ["aerosol particle phase", "PM10", "PM2.5"]
ebas_component = ["sulphate_total"]
ebas_matrix = ["aerosol", "pm10", "pm25"]
standard_names = ["mass_concentration_of_total_sulphateexpressed_as_sulphur_in_dry_aerosol_particles_in_air",
    "mass_concentration_of_sulphate_total_in_pm10_in_air",
    "mass_concentration_of_sulphate_total_in_pm2p5_in_air", ]

[variables.concso4c]
actris_variable = ["aerosol particle sulphate mass concentration"]
actris_matrix = ["aerosol particle phase", "PM10", "PM2.5"]
ebas_component = ["sulphate_corrected"]
ebas_matrix = ["aerosol", "pm10", "pm25"]
standard_names = ["mass_concentration_of_sulphate_corrected_for_seaspray_expressed_as_sulphur_in_dry_aerosol_particles_in_air",
    "mass_concentration_of_sulphate_corrected_for_seaspray_expressed_as_sulphur_in_pm10_in_air",
    "mass_concentration_of_sulphate_corrected_for_seaspray_expressed_as_sulphur_in_pm2p5_in_air", ]

[variables.concCecpm25]
actris_variable = ["aerosol particle elemental carbon mass concentration"]
actris_matrix = ["aerosol particle phase"]
ebas_component = ["elemental_carbon"]
ebas_matrix = ["pm25", "pm1"]
standard_names = ["mass_concentration_of_elemental_carbon_in_pm2p5_in_air",
    "mass_concentration_of_elemental_carbon_in_pm1_in_air", ]

[variables.concCsopm25]
actris_variable = ["aerosol particle organic carbon mass concentration"]
actris_matrix = ["aerosol particle phase"]
ebas_component = ["organic_carbon"]
ebas_matrix = ["pm25", "pm1"]
standard_names = ["mass_concentration_of_organic_carbon_in_pm2p5_in_air",
    "mass_concentration_of_organic_carbon_in_pm1_in_air", ]

#[actris_std_units]
# tell the reader which unit shall be returned in case the same property is available in several units
# e.g. ozone mass concentration is available in the files in [ug/m3] and [nmol/mol]
# make sure to use ACTRIS-EBAS unit notation since this is a simple string match
# For variables not noted here, we will return the first unit found in the first data file
#"ozone mass concentration" = "ug/m3"
#"ozone amount fraction" = "nmol/mol"
#"aerosol particle sulphate mass concentration" = "ug/m3"

[actris_standard_names]
# match between ACTRIS vocabulary and CF standard name
# needed to match the variables in multicolumn files since the netcdf variable name has no meaning
# the standard_names are not unique for a given ACTRIS species, therefore a list
"ozone mass concentration" = ["mass_concentration_of_ozone_in_air"]
"ozone amount fraction" = ["mole_fraction_of_ozone_in_air"]
"aerosol particle sulphate mass concentration" = ["mass_concentration_of_total_sulphateexpressed_as_sulphur_in_dry_aerosol_particles_in_air",
    "mass_concentration_of_sulphate_total_in_pm10_in_air",
    "mass_concentration_of_sulphate_total_in_pm2p5_in_air", ]
#"" = "mass_concentration_of_sulphate_corrected_for_seaspray_expressed_as_sulphur_in_dry_aerosol_particles_in_air"
#"" = ""
#"" = ""
"aerosol particle elemental carbon mass concentration" = ["mass_concentration_of_elemental_carbon_in_pm2p5_in_air",
    "mass_concentration_of_elemental_carbon_in_pm1_in_air", ]
"aerosol particle organic carbon mass concentration" = ["mass_concentration_of_organic_carbon_in_pm2p5_in_air",
    "mass_concentration_of_organic_carbon_in_pm1_in_air", ]
